services:
  petclinic:
    build:
      context: .
      dockerfile: Dockerfile.two
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=petclinic
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

